name: develop-quality
"on":
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          config: .github/.markdownlint.json
          globs: "**/*.md"

      - name: Spelling check
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: .github/.cspell.json
          files: "**/*.md"
